---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata: 
        name: Fluentd
rules:
       - apiGroups:
         - ""
         resources:
          - pods
         verbs:
          - get
          - list
