---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
        name: prometheus
        labels:
                app: prometheus
rules:
- apiGroups:
        - "" 
  resources:
          - nodes
          - nodes/proxy
          - pods
          - endpoints
          - services

  verbs:
        - get
        - list
        - watch
- nonResourceURLs:
        - /metrics
  verbs:
        - get
