---
apiVersion: v1
kind: Service
metadata:
        name: prometheus
        namespace: sretest
        annotations:
                prometheus.io/scrape: 'true'
        labels:
                name: prometheus
spec:
        selector:
                app: prometheus
        type: nodePort
        ports:
                - name: prometheus
                  protocol: TCP
                  port: 9090
                  targetPort: 9090
                  nodePort: 31090

