---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
        name: prometheus-deployment
        namespace: sretest
spec:
        replicas: 1
        selector:
                matchLabels:
                        app: prometheus
        template:
                metadata:
                        name: prometheus
                        labels:
                                app: prometheus
                spec:
                        serviceAccount: prometheus
                        containers:
                           - name: prometheus
                             image: prom/prometheus:v1.5.2
                             args:
                                     - '-storage.local.retention=360h'
                                     - '-storage.local.memory-chunks=1048576'
                                     - '-config.file=/etc/prometheus/prometheus.yml'
                                     - '-alertmanager.url=http://alertmanager:9093'
                        ports:
                          - name: web
                            containerPort: 9090
                        volumeMounts:
                          - name: config-Volume
                            path: /etc/prometheus
                          - name: alertrules-volume
                            path: /etc/prometheus-rules
                volume:
                        - name: config-Volume
                          configMap: prometheus-configmap
                        - name: alertrules-volume
                          configMap: prometheus-alertrules

