---
apiversion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
        name: prometheus
        labels:
                app: prometheus
roleref:
        apiGroups: rbac.authorization.k8s.io
        kind: ClusterRole
        name: prometheus
subjects:
- kind: ServiceAccount
  name: prometheus
  namespace: sretest
