---
apiVersion: v1
kind: Service
metadata:
        name: dummy-pdf-or-png-svc
spec:
        type: LoadBalancer
        ports:
        - name: http
          port: 9090
          targetPort: 3000
        selector:
                app: dummypdfpng
